import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Seifu Baks Driving School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-B4gt1jrGC7Jh4Agf6g9Qbg3P0E4Wl7lTwOOGX1D3GaPU6pLFxT4vHgJBRXtv4j2K"
            crossOrigin="anonymous"
          />
      </head>
      <body className={inter.className}>

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossOrigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossOrigin="anonymous"></script>
        
      <nav className ="navbar navbar-expand-lg bg-body-tertiary">
        <div className ="container-fluid">
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ6ApFXqU1S0rGVn-UJwHAUqB_iMiBQrohng&s" alt="Bootstrap" width="50" height="50"/>
              <a className ="navbar-brand" href="/">Seifu Baks Driving School</a>
              <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                  <li className="nav-item">
                    <a className="nav-link active" aria-current="page" href="/">Home</a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/webpages">Fuel Form</a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/webpages/oilform">Oil Form</a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/#">Student Files</a>
                  </li>
                </ul>
                <form className="d-flex" role="search">
                  <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                  <button className="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
          </div>
        </nav>
        
        {children}
        </body>
    </html>
  );
}
